#version: '3.1'
#services:
#  db:
#    image: mongodb
#    container_name: capitalmilenio_mongodb_container
#    environment:
#      mongodb_root_password: root
#
#    ports:
#      - "3306:3306"
#    volumes:
#      - capitalmilenio_data:/var/lib/mongodb
#volumes:
#  capitalmilenio_data: