  version: "3.7"
  services:
    mileniocapitaldesafiomongodb:
      build: .
      restart: always
      ports:
        - 8080:8080
      links:
        - mongo-on-docker
      depends_on:
        - mongo-on-docker
    mongo-on-docker:
      image: "mongo:latest"
      restart: always
      ports:
        - 27017:27017